### ISSUE TITLE
numpy.std causes an error with Quantity class 

### ISSUE THREAD

**Issue by robertjperry** [ILAFF/ILAFF#22]
Calculating the mean with numpy works as expected,
```
>>> lat=units.Lattice()
>>> test=np.array([1,2,3,4])*units.a(lat)
>>> np.mean(test)
Quantity(value=2.5, dimension=Dimension(mass_dim=-1), scale=Lattice())
```

But the standard deviation does not.

```
>>> np.std(test)
AttributeError: 'Quantity' object has no attribute 'conjugate'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 5, in std
  File "/home/rperry/anaconda2/envs/py38/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 3496, in std
    return _methods._std(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
  File "/home/rperry/anaconda2/envs/py38/lib/python3.8/site-packages/numpy/core/_methods.py", line 233, in _std
    ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
  File "/home/rperry/anaconda2/envs/py38/lib/python3.8/site-packages/numpy/core/_methods.py", line 214, in _var
    x = um.multiply(x, um.conjugate(x), out=x).real
TypeError: loop of ufunc does not support argument 0 of type Quantity which has no callable conjugate method

```

**Comment by RJaBi** [comment]
I could be completely up the wrong tree here, but my thoughts are that it's converting the quantity of np array to an array of Quantity's which is the issue. Hence it tries to take a conjugate of an array of Quantity's and doesn't know how.

i.e.

```
>>> from ilaff import units 
>>> import numpy as np  
>>> lat=units.Lattice()  
>>> test=np.array([1,2,3,4])*units.a(lat) 
>>> np.mean(test) 
Quantity(value=2.5, dimension=Dimension(mass_dim=-1), scale=Lattice())  
>>> np.asarray(test) 
array([Quantity(value=1.0, dimension=Dimension(mass_dim=-1), scale=Lattice()),  
       Quantity(value=2.0, dimension=Dimension(mass_dim=-1), scale=Lattice()),    
       Quantity(value=3.0, dimension=Dimension(mass_dim=-1), scale=Lattice()),   
       Quantity(value=4.0, dimension=Dimension(mass_dim=-1), scale=Lattice())], 
      dtype=object)
```

i.e. before the asarray it works and after it doesn't.
```
>>> np.conjugate(test) 
Quantity(value=array([1., 2., 3., 4.]), dimension=Dimension(mass_dim=-1), scale=Lattice()) 
>>> np.conjugate( np.asarray(test) ) 
AttributeError: 'Quantity' object has no attribute 'conjugate'   
  
The above exception was the direct cause of the following exception:   
    
Traceback (most recent call last):  
  File "<stdin>", line 1, in <module>    
TypeError: loop of ufunc does not support argument 0 of type Quantity which has no callable conjugate method  
```

Note that `np.array(test)` and `np.asanyarray(test)` here produce identical behaviour to `np.asarray`

I guess the solution is to make `np.array()`, etc work differently?

**Comment by FinnStokes** [comment]
Ryan is right, the `np.std` implementation is calling `asarray` on the quantity, which breaks our encapsulation. This happens because `np.std` (along with a few other numpy functions) does not use the ufunc machinery that most of numpy uses. I think the solution is to implement methods like `std` on the `Quantity` class to handle the unwrapping/rewrapping, and then numpy should recognise them and use them properly.
